version: '3.8'

services:
  whisper-gpu:
    build: 
      context: .
      dockerfile: Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - VIRTUAL_HOST=zizka.praut.cz
      - VIRTUAL_PORT=18666
      - LETSENCRYPT_HOST=zizka.praut.cz
    ports:
      - "18666:18666"
    volumes:
      - whisper-data:/appold
      - whisper-models:/appold/models
    restart: unless-stopped

volumes:
  whisper-data:
  whisper-models: